version: '3.3'
networks:
  spring-boot-mysql-network:
    driver: bridge
services:
  message-broker:
    image: rabbitmq:3.8-management
    hostname: message-broker
    restart: always
    labels:
      NAME: message-broker
    ports:
      - "15672:15672"
      - "5672:5672"

  spring-gateway:
    image: spring-gateway:latest
    hostname: spring-gateway
    restart: always
    ports:
        - 8083:8083

  lobby-service:
    image: lobby-service:latest
    hostname: lobby-service
    restart: always
    ports:
      - 8082:8082

  mysqldb:
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: 'gbf'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3307:3306
      # Where our data will be persisted
    networks:
      - spring-boot-mysql-network
    volumes:
      - ./my-db:/var/lib/mysql

  authentication-service:
    image: authentication-service:latest
    hostname: authentication-service
    restart: always
    ports:
      - 8081:8081
    links:
      - mysqldb:mysqldb
    depends_on:
      - mysqldb
    networks:
      - spring-boot-mysql-network
