apiVersion: v1
kind: Service
metadata:
  name: authdb
spec:
  ports:
    - port: 3306
  selector:
    app: authdb
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: authdb
spec:
  selector:
    matchLabels:
      app: authdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: authdb
    spec:
      containers:
        - image: mysql:8.0.20
          name: authdb
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: 'admin'
            - name: MYSQL_DATABASE
              value: 'gbf'
            - name: MYSQL_USER
              value: 'myuser'
            - name: MYSQL_PASSWORD
              value: 'myuser'
          ports:
            - containerPort: 3306
              name: authdb
---
apiVersion: v1
kind: Service
metadata:
  name: lobbydb
spec:
  ports:
    - port: 3306
  selector:
    app: lobbydb
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: lobbydb
spec:
  selector:
    matchLabels:
      app: lobbydb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lobbydb
    spec:
      containers:
        - image: mysql:8.0.20
          name: lobbydb
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: 'admin'
            - name: MYSQL_DATABASE
              value: 'lobby'
            - name: MYSQL_USER
              value: 'myuser'
            - name: MYSQL_PASSWORD
              value: 'myuser'
          ports:
            - containerPort: 3306
              name: lobbydb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-broker
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: message-broker
          image: rabbitmq:3.8-management
          ports:
            - containerPort: 5672
              name: message-broker
---
apiVersion: v1
kind: Service
metadata:
  name: message-broker
spec:
  type: LoadBalancer
  ports:
    - port: 5672
  selector:
    app: message-broker
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: auth-service
          image: mycontainerregistry1610.azurecr.io/auth-service:kube
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 8081
              name: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
  selector:
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lobby-service
  template:
    metadata:
      labels:
        app: lobby-service
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: lobby-service
          image: mycontainerregistry1610.azurecr.io/lobby-service:kube
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 8082
          env:
            - name: auth-service
              value: "auth-service"
---
apiVersion: v1
kind: Service
metadata:
  name: lobby-service
spec:
  type: LoadBalancer
  ports:
    - port: 8082
  selector:
    app: lobby-service
